<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jifa</groupId>
    <artifactId>jifa</artifactId>
        <version>0.3.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>heap-dump-analysis-hook</artifactId>
  <properties>
    <mat.deps.dir>${maven.multiModuleProjectDirectory}/analysis/heap-dump/provider/src/main/resources/mat-deps</mat.deps.dir>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jifa.mat</groupId>
      <artifactId>mat-hprof</artifactId>
      <version>1.16.1</version>
      <scope>system</scope>
      <systemPath>${mat.deps.dir}/org.eclipse.mat.hprof_1.16.1.202501091339.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa.mat</groupId>
      <artifactId>eclipse-core-runtime</artifactId>
      <version>3.32.0</version>
      <scope>system</scope>
      <systemPath>${mat.deps.dir}/org.eclipse.core.runtime-3.32.0.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa.mat</groupId>
      <artifactId>equinox-preferences</artifactId>
      <version>3.11.200</version>
      <scope>system</scope>
      <systemPath>${mat.deps.dir}/org.eclipse.equinox.preferences-3.11.200.jar</systemPath>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa.mat</groupId>
      <artifactId>equinox-osgi</artifactId>
      <version>3.22.0</version>
      <scope>system</scope>
      <systemPath>${mat.deps.dir}/org.eclipse.osgi-3.22.0.jar</systemPath>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>package-for-provider-tests</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <classifier>reactor</classifier>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
