<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.jifa</groupId>
    <artifactId>jifa</artifactId>
        <version>0.3.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
  </parent>
  <artifactId>heap-dump-analysis-provider</artifactId>
  <properties>
    <mat.deps.dir>${maven.multiModuleProjectDirectory}/analysis/heap-dump/provider/src/main/resources/mat-deps</mat.deps.dir>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.jifa</groupId>
      <artifactId>analysis</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa</groupId>
      <artifactId>heap-dump-analysis-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa</groupId>
      <artifactId>heap-dump-analysis-impl</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa</groupId>
      <artifactId>heap-dump-analysis-hook</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jifa.mat</groupId>
      <artifactId>equinox-osgi</artifactId>
      <version>3.22.0</version>
      <scope>system</scope>
      <systemPath>${mat.deps.dir}/org.eclipse.osgi-3.22.0.jar</systemPath>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-heap-dump-implementation-integration-tests</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.basedir}/../impl/src/test/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-heap-dump-implementation-into-mat-deps</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.eclipse.jifa</groupId>
                  <artifactId>heap-dump-analysis-impl</artifactId>
                  <version>${project.version}</version>
                  <classifier>reactor</classifier>
                  <outputDirectory>${project.build.outputDirectory}/mat-deps</outputDirectory>
                  <destFileName>heap-dump-analysis-impl-${project.version}.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
          <execution>
            <id>unpack-heap-dump-hook</id>
            <phase>process-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.eclipse.jifa</groupId>
                  <artifactId>heap-dump-analysis-hook</artifactId>
                  <version>${project.version}</version>
                  <classifier>reactor</classifier>
                  <outputDirectory>${project.build.directory}/heap-dump-hook</outputDirectory>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>patch-hprof-preferences</id>
            <phase>process-resources</phase>
            <configuration>
              <target>
                <jar destfile="${project.build.outputDirectory}/mat-deps/org.eclipse.mat.hprof_1.16.1.202501091339.jar" update="true">
                  <fileset dir="${project.build.directory}/heap-dump-hook" includes="org/eclipse/mat/hprof/**"/>
                </jar>
              </target>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
